name: Lint and Compile
on:
  - push
  - pull_request

jobs:
  compile:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add msbuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Restore NuGet Packages
        run: nuget restore ${{ github.event.repository.name }}.sln
      - name: Compile
        working-directory: ${{ env.GITHUB_WORKSPACE }}
        run: msbuild -m -p:Configuration=${{ matrix.configuration }} ${{ github.event.repository.name }}.sln
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}.${{ matrix.configuration }}
          path: ${{ env.GITHUB_WORKSPACE }}/bin/${{ matrix.configuration }}
